  server:
    port: 8082

  spring:
    application:
      name: log-integrator
    datasource:
      url: jdbc:h2:file:./data/db/errors
      username: sa
      driver-class-name: org.h2.Driver
    flyway:
      locations: classpath:db/migration
      schemas: PUBLIC
      baseline-on-migrate: true
    kafka:
      bootstrap-servers: localhost:9092
      admin:
        fail-fast: true
      consumer:
        group-id: log-integrator
        key-deserializer: "org.apache.kafka.common.serialization.StringDeserializer"
        value-deserializer: "org.springframework.kafka.support.serializer.JsonDeserializer"
        properties:
          spring:
            json:
              trusted:
                packages: '*'
              value:
                default:
                  type: "ru.hehmdalolkek.logintegrator.dto.RequestLogDto"

  broker:
    kafka:
      topics:
        errors:
          name: errors