server:
  port: 8081

spring:
  application:
    name: log-handler
  kafka:
    bootstrap-servers: localhost:9092
    admin:
      fail-fast: true
    streams:
      application-id: log-handler
  boot:
    admin:
      client:
        url: http://localhost:8083

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    env:
      show-values: always

broker:
  kafka:
    topics:
      logs:
        name: logs
      errors:
        name: errors

notification:
  errors:
    duration: 600
    limit: 5
