server:
  port: 8081

spring:
  application:
    name: log-handler
  kafka:
    bootstrap-servers: localhost:9092
    admin:
      fail-fast: true
    streams:
      application-id: log-handler

broker:
  kafka:
    topics:
      logs:
        name: logs
      errors:
        name: errors

notification:
  errors:
    duration: 600
    limit: 5
